package com.eventosdahora.orquestrador.sagas.dominio;

public enum PedidoEvent {
    RESERVAR_TICKET, RESERVA_TICKET_APROVADO, RESERVA_TICKET_NEGADO,
    PAGAR_TICKET_APROVADO, PAGAR_TICKET_NEGADO,
    CONSOLIDACAO_COMPRA_APROVADO,
    TICKET_RESTAURADO_SUCESSO, TICKET_RESTAURADO_NEGADO

}
